# Messages
cant_find_player: '&7Player not found.'
teleported_message: '&7Teleported to %Player%'
teleported_message_admin: '&7Teleported %Player% to %Player2%.'
teleport_specify: '&7Please specify a player. /tp <player>'
reloaded_message: '&7Reloaded configuration file'
no_mr_perez: '&7You cannot teleport others man.. come on.. /tp <player>'
no_permission: '&7You do not have permission use this command.'

# Call out Perez

callout_mr_perez: '&7&l&nCmon %Player%, you cant teleport others! Learn not to abuse this power!'

# Perms
reload_permission: 'snubs.tpreload'
permission_admin_tp: 'snubs.admin'
permission_tp: 'snubs.tp'

# Torture Players
players:
   - "OG_Perez"
   # - "Player2" add more players here