name: PreventTP
main: com.snubs.preventtp.Main
version: 1.5
commands:
  tp:
    description: Teleport to a player.
  tpn:
    description: Teleport to a player/Teleport others.
  tppunish:
    description: Add player to the punishment list. (Gets nausea when trying to teleport others)
  tpreload:
    description: Reloads the config file.